### PR TITLE
Add growth and growth ranks

### LINKED ISSUE #160: Fix growth interval
See https://github.com/georgetown-cset/parat/issues/92

### LINKED ISSUE #161: Pre-calculate growth metrics and generate rank

### PR DESCRIPTION
**Pull request by jmelot**
Does this work for you Brian? I added them as though they were another normal metric, but without yearly counts. The name of the metric should change to something like "Average yearly growth, past three years" (thoughts on wording @za158? This is `((year_4-year_3)+(year_3-year_2)+(year_2-year_1))/3`, with an offset to cut off the incomplete data interval. I think it's a better metric than just diffing the start and end of the interval)

Closes #161 
Closes #160

### CODE REVIEW

**Comment by za158** [comment]
If it's going to serve as a column header, it needs to be shorter than that...in that context let's say "Recent yearly growth" with a tooltip with a fuller explanation. Your terminology is fine other than that I think

**Comment by brianlove** [comment]
@jmelot This is generating growth stats for AI publications and patents, but the only growth column that I'm seeing/remembering in PARAT is growth of _all_ publications/patents, not just AI ("_5-year growth in publications_" and "_5-year growth in patents_" in the current GUI).  Is the plan now to just have growth for AI and not all pubs/patents, or is that part still to come?

**Comment by jmelot** [comment]
Oh -- in the detail view the text suggests it's growth in AI patents and pubs, but now that I look at the list view metrics more closely I see that they reference total publications. Since PARAT is focused on AI I think the former makes sense if we're going to display one growth metric for each of pubs and patents. It's very easy to switch over, or generate both, though. @za158 any opinion

**Comment by za158** [comment]
Yes everything in PARAT is AI-focused, to the extent that we don't bother to specify "AI" in many/most instances of text

**Comment by brianlove** [comment]
@jmelot I appear to have misinterpreted what these columns represent.  When I saw the columns named "growth" I assumed that these were _percentage_ growth over the given timespan, but after diagnosing an issue with several companies (including Google) disappearing, I've realized that these are actually just the raw average changes over the 3-year timespan.  Given that, I'm not sure "_growth_" is the right naming for these columns - perhaps "change" or "delta" would be better?

**Review by brianlove — APPROVED** [review]
@jmelot data updates look good; I've added relevant UI changes, so feel free to merge once you've reviewed those.

**Comment by jmelot** [comment]
@brianlove fixed up the metric; ui changes look good once you revert the column name change. Can you add this to the detail view as well? I think we have placeholders for these growth metrics in the publication and patents sections

**Review by brianlove — APPROVED** [review]
👍  Looks good; UI now reflects percentages and added growth to detail page

**Pull request merged**
