### PR TITLE
Use business sector

### LINKED ISSUE #236: Change basis of "Sector" field
from TRBC/PermID "Primary Economic Sector" to "Primary Business Sector"

https://www.equidam.com/resources/trbc-fact-sheet.pdf

eg, Microsoft should be "Software & IT Services," not "Technology"

### LINKED ISSUE #247: Microsoft's sector is listed as "Healthcare"
image

ER issue somewhere, I think; compare https://permid.org/1-4295907168

### PR DESCRIPTION
**Pull request by jmelot**
Closes #236 
Closes #247 

@za158 and @rggelles the first thing I need from you all is an opinion on what to do with multiple permids - the code is likely to change after we make this decision so I'd hold off on reviewing it for now. Currently, we are taking the sector of the first permid that has a sector. This leads to some weird results like Microsoft being assigned to the "Pharmaceuticals & Medical Research" sector because one of the orgs that was rolled up into Microsoft has that sector. 

Do you have a preference among these three options:

1. Keep current method
2. Take most common sector among all permids
3. Keep all sectors, ask Brian to update column to display all sectors + make all sectors an org has searchable

@brianlove for situational awareness

### CODE REVIEW

**Comment by za158** [comment]
Is the issue confined to rollups? If so, is there any way to always select
the permid of the topmost entity?
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory (web <http://eto.tech> |
LinkedIn <https://www.linkedin.com/company/emerging-technology-observatory>
| Substack <http://etoblog.substack.com>)
Center for Security and Emerging Technology
***@***.***

**Comment by jmelot** [comment]
(documenting what we decided irl earlier) Rebecca will provide the permid of the topmost entity, and I'll update the data preprocessing script to use this new field

**Comment by rggelles** [comment]
@jmelot back to you on this one, I think. The parent/child permid should be separable now.

**Review by jmelot — COMMENTED** [review]
👍 read over this commit, looks good

**Comment by jmelot** [comment]
@rggelles ok I think I've finished up here - can you please review? I'll address the id update in a separate PR

**Review by rggelles — APPROVED** [review]
LGTM!

**Pull request merged**
