### PR TITLE
Add user-defined groups of companies

### LINKED ISSUE #13: Add ability to create user-defined groups of companies
Allow users to select a specific subset of companies (for example, their main competitors) to view in the list view and get aggregate metrics of.

### PR DESCRIPTION
**Pull request by brianlove**
Add a case for custom, user-defined groups of companies and a dialog to select the companies to be included.

Closes #13

### CODE REVIEW

**Review by niharikasingh — APPROVED** [review]
A few comments on the UI: 

1. The list of companies in the modal doesn't seem to be ordered in any particular way. 
2. In the custom companies modal, if I add companies and then click "Cancel" the modal closes as expected. However, if I open the modal again, the companies I added but did not apply still appear. I expect these companies to not be saved in the dropdown selector if I click "Cancel". 
3. "User-Defined" seems like clunky wording for the dropdown. I'm not sure our users refer to themselves that way. Maybe something like "Custom" instead?

**Review by jmelot — COMMENTED** [review]
I don't see issues with this code, but I'll make some follow-up comments on the design in the main thread.

**Comment by jmelot** [comment]
Screenshot 2023-09-05 at 9 06 34 AM

I only realized that you had custom text here when I read the code - I screenshotted this when I saw "No results found" to suggest that you change the text to something custom, like what you have in the small text underneath. I think the larger text needs to change as well as it's the first thing a user is going to read.

Screenshot 2023-09-05 at 9 06 44 AM

Still seeing dropdown overflow

Screenshot 2023-09-05 at 9 07 22 AM

I want @za158's take before I suggest you make changes, but I don't think the modal is intuitive. I didn't notice the custom groups button at first and tried to add companies this way. 

Screenshot 2023-09-05 at 9 07 33 AM

There's more dropdown overflow in the modal

Screenshot 2023-09-05 at 9 15 47 AM

The custom group does not reset when I click "reset filters" - this may lead to confusing behavior if e.g. people share a link without realizing an old custom group is selected

See what you think about those comments. If anything jumps out at you you could go ahead and implement it, otherwise let's merge this as a starting point and then I'll ask for Zach's take on the dev site.

**Comment by jmelot** [comment]
> "User-Defined" seems like clunky wording for the dropdown. I'm not sure our users refer to themselves that way. Maybe something like "Custom" instead?

Also, I'm glad you've addressed this - I didn't pull before I reviewed/screenshotted (just realized there was a new commit), but just checked and it looks like my comments above still stand

**Comment by brianlove** [comment]
I've updated the text displayed when there are no results and made sure the menus overflow their containers.

I don't think that the 'reset filters' button should reset the custom group - a user may have their custom group, do some filtering on that, and then want to return to the full group, and I don't think they would expect that clicking 'reset' would wipe out the full group.  Regarding the sharing of a URL containing a custom group, I updated the group handling so that the URL will only display group membership when the user is viewing a custom group (other times it's saved in an internal state variable).

**Pull request merged**
