### PR TITLE
Update workforce count wording

### PR DESCRIPTION
**Pull request by jmelot**
@rggelles can you confirm this is what you wanted
@za158 can you review
@brianlove can you review and merge after they're done

Screenshot 2024-06-26 at 1 43 10 PM

### CODE REVIEW

**Comment by za158** [comment]
I will make some stylistic edits and conform some tooltips once @rggelles confirms that the revised phrasing is accurate

**Review by rggelles — APPROVED** [review]
Looks good to me, yes!

**Comment by za158** [comment]
done here

**Review by za158 — APPROVED** [review]

**Review by brianlove — APPROVED** [review]
👍

**Pull request merged**
