### PR TITLE
Hide the rank when the value is zero

### LINKED ISSUE #106: Don't display rank when field value = 0
as here
image

### PR DESCRIPTION
**Pull request by brianlove**
Closes #106

### CODE REVIEW

**Review by jmelot — COMMENTED** [review]
👍 this is correctly implemented as described

@za158 I think this looks kind of weird. Should we be using an N/A or something instead of removing the rank altogether

Screenshot 2023-09-26 at 11 00 22 AM

**Comment by brianlove** [comment]
Another option instead of "N/A" would be "---", which would provide something there while still being distinct enough to let users see that there is no rank:

**Comment by za158** [comment]
I like Brian's suggestion

**Comment by jmelot** [comment]
Me too :shipit:

**Pull request merged**
